// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: user.proto

package userapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Users_Create_FullMethodName                     = "/userapi.Users/Create"
	Users_Get_FullMethodName                        = "/userapi.Users/Get"
	Users_Update_FullMethodName                     = "/userapi.Users/Update"
	Users_Find_FullMethodName                       = "/userapi.Users/Find"
	Users_Delete_FullMethodName                     = "/userapi.Users/Delete"
	Users_LogEvent_FullMethodName                   = "/userapi.Users/LogEvent"
	Users_AddAttribute_FullMethodName               = "/userapi.Users/AddAttribute"
	Users_AddTrait_FullMethodName                   = "/userapi.Users/AddTrait"
	Users_DeleteAttribute_FullMethodName            = "/userapi.Users/DeleteAttribute"
	Users_DeleteTrait_FullMethodName                = "/userapi.Users/DeleteTrait"
	Users_SearchUserTraits_FullMethodName           = "/userapi.Users/SearchUserTraits"
	Users_GetUsersByTraits_FullMethodName           = "/userapi.Users/GetUsersByTraits"
	Users_GetUsersByAggregatedTraits_FullMethodName = "/userapi.Users/GetUsersByAggregatedTraits"
	Users_GetAggregateForUsers_FullMethodName       = "/userapi.Users/GetAggregateForUsers"
	Users_GetUsersByEvents_FullMethodName           = "/userapi.Users/GetUsersByEvents"
	Users_SearchEvents_FullMethodName               = "/userapi.Users/SearchEvents"
	Users_NaturalBreaks_FullMethodName              = "/userapi.Users/NaturalBreaks"
	Users_NaturalBreaksQueried_FullMethodName       = "/userapi.Users/NaturalBreaksQueried"
	Users_QueryUsers_FullMethodName                 = "/userapi.Users/QueryUsers"
	Users_QueryAttributes_FullMethodName            = "/userapi.Users/QueryAttributes"
	Users_QueryTraits_FullMethodName                = "/userapi.Users/QueryTraits"
	Users_QueryEvents_FullMethodName                = "/userapi.Users/QueryEvents"
	Users_AddSession_FullMethodName                 = "/userapi.Users/AddSession"
	Users_IdentifySession_FullMethodName            = "/userapi.Users/IdentifySession"
	Users_GetSessions_FullMethodName                = "/userapi.Users/GetSessions"
	Users_LogSessionEvent_FullMethodName            = "/userapi.Users/LogSessionEvent"
	Users_GetSessionEvents_FullMethodName           = "/userapi.Users/GetSessionEvents"
)

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersClient interface {
	Create(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*UserResponse, error)
	Get(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Update(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Find(ctx context.Context, in *UserQuery, opts ...grpc.CallOption) (*UserListResponse, error)
	Delete(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	LogEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	AddAttribute(ctx context.Context, in *AttributeRequest, opts ...grpc.CallOption) (*AttributeResponse, error)
	AddTrait(ctx context.Context, in *TraitRequest, opts ...grpc.CallOption) (*TraitResponse, error)
	DeleteAttribute(ctx context.Context, in *AttributeRequest, opts ...grpc.CallOption) (*AttributeResponse, error)
	DeleteTrait(ctx context.Context, in *TraitRequest, opts ...grpc.CallOption) (*TraitResponse, error)
	SearchUserTraits(ctx context.Context, in *SearchUserTraitsRequest, opts ...grpc.CallOption) (*SearchUserTraitsResponse, error)
	GetUsersByTraits(ctx context.Context, in *SearchUserTraitsRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	GetUsersByAggregatedTraits(ctx context.Context, in *GetUsersByAggregatedTraitsRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	GetAggregateForUsers(ctx context.Context, in *GetAggregateForUsersRequest, opts ...grpc.CallOption) (*AggregateResponse, error)
	GetUsersByEvents(ctx context.Context, in *SearchUserEventsRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	NaturalBreaks(ctx context.Context, in *NaturalBreaksRequest, opts ...grpc.CallOption) (*NaturalBreaksResponse, error)
	NaturalBreaksQueried(ctx context.Context, in *NaturalBreaksQueryRequest, opts ...grpc.CallOption) (*NaturalBreaksResponse, error)
	QueryUsers(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	QueryAttributes(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*AttributeListResponse, error)
	QueryTraits(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*TraitListResponse, error)
	QueryEvents(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	AddSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	IdentifySession(ctx context.Context, in *IdentifySessionRequest, opts ...grpc.CallOption) (*IdentifySessionResponse, error)
	GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*SessionListResponse, error)
	LogSessionEvent(ctx context.Context, in *SessionEventRequest, opts ...grpc.CallOption) (*SessionEventResponse, error)
	GetSessionEvents(ctx context.Context, in *GetSessionEventsRequest, opts ...grpc.CallOption) (*SessionEventListResponse, error)
}

type usersClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersClient(cc grpc.ClientConnInterface) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Create(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, Users_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Get(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, Users_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Update(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, Users_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Find(ctx context.Context, in *UserQuery, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, Users_Find_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Delete(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, Users_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) LogEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, Users_LogEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) AddAttribute(ctx context.Context, in *AttributeRequest, opts ...grpc.CallOption) (*AttributeResponse, error) {
	out := new(AttributeResponse)
	err := c.cc.Invoke(ctx, Users_AddAttribute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) AddTrait(ctx context.Context, in *TraitRequest, opts ...grpc.CallOption) (*TraitResponse, error) {
	out := new(TraitResponse)
	err := c.cc.Invoke(ctx, Users_AddTrait_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteAttribute(ctx context.Context, in *AttributeRequest, opts ...grpc.CallOption) (*AttributeResponse, error) {
	out := new(AttributeResponse)
	err := c.cc.Invoke(ctx, Users_DeleteAttribute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteTrait(ctx context.Context, in *TraitRequest, opts ...grpc.CallOption) (*TraitResponse, error) {
	out := new(TraitResponse)
	err := c.cc.Invoke(ctx, Users_DeleteTrait_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SearchUserTraits(ctx context.Context, in *SearchUserTraitsRequest, opts ...grpc.CallOption) (*SearchUserTraitsResponse, error) {
	out := new(SearchUserTraitsResponse)
	err := c.cc.Invoke(ctx, Users_SearchUserTraits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUsersByTraits(ctx context.Context, in *SearchUserTraitsRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, Users_GetUsersByTraits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUsersByAggregatedTraits(ctx context.Context, in *GetUsersByAggregatedTraitsRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, Users_GetUsersByAggregatedTraits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetAggregateForUsers(ctx context.Context, in *GetAggregateForUsersRequest, opts ...grpc.CallOption) (*AggregateResponse, error) {
	out := new(AggregateResponse)
	err := c.cc.Invoke(ctx, Users_GetAggregateForUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetUsersByEvents(ctx context.Context, in *SearchUserEventsRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, Users_GetUsersByEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, Users_SearchEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) NaturalBreaks(ctx context.Context, in *NaturalBreaksRequest, opts ...grpc.CallOption) (*NaturalBreaksResponse, error) {
	out := new(NaturalBreaksResponse)
	err := c.cc.Invoke(ctx, Users_NaturalBreaks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) NaturalBreaksQueried(ctx context.Context, in *NaturalBreaksQueryRequest, opts ...grpc.CallOption) (*NaturalBreaksResponse, error) {
	out := new(NaturalBreaksResponse)
	err := c.cc.Invoke(ctx, Users_NaturalBreaksQueried_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) QueryUsers(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, Users_QueryUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) QueryAttributes(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*AttributeListResponse, error) {
	out := new(AttributeListResponse)
	err := c.cc.Invoke(ctx, Users_QueryAttributes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) QueryTraits(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*TraitListResponse, error) {
	out := new(TraitListResponse)
	err := c.cc.Invoke(ctx, Users_QueryTraits_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) QueryEvents(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, Users_QueryEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) AddSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, Users_AddSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) IdentifySession(ctx context.Context, in *IdentifySessionRequest, opts ...grpc.CallOption) (*IdentifySessionResponse, error) {
	out := new(IdentifySessionResponse)
	err := c.cc.Invoke(ctx, Users_IdentifySession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetSessions(ctx context.Context, in *GetSessionsRequest, opts ...grpc.CallOption) (*SessionListResponse, error) {
	out := new(SessionListResponse)
	err := c.cc.Invoke(ctx, Users_GetSessions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) LogSessionEvent(ctx context.Context, in *SessionEventRequest, opts ...grpc.CallOption) (*SessionEventResponse, error) {
	out := new(SessionEventResponse)
	err := c.cc.Invoke(ctx, Users_LogSessionEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) GetSessionEvents(ctx context.Context, in *GetSessionEventsRequest, opts ...grpc.CallOption) (*SessionEventListResponse, error) {
	out := new(SessionEventListResponse)
	err := c.cc.Invoke(ctx, Users_GetSessionEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
// All implementations must embed UnimplementedUsersServer
// for forward compatibility
type UsersServer interface {
	Create(context.Context, *NewUser) (*UserResponse, error)
	Get(context.Context, *UserRequest) (*UserResponse, error)
	Update(context.Context, *UserRequest) (*UserResponse, error)
	Find(context.Context, *UserQuery) (*UserListResponse, error)
	Delete(context.Context, *UserRequest) (*UserResponse, error)
	LogEvent(context.Context, *EventRequest) (*EventResponse, error)
	AddAttribute(context.Context, *AttributeRequest) (*AttributeResponse, error)
	AddTrait(context.Context, *TraitRequest) (*TraitResponse, error)
	DeleteAttribute(context.Context, *AttributeRequest) (*AttributeResponse, error)
	DeleteTrait(context.Context, *TraitRequest) (*TraitResponse, error)
	SearchUserTraits(context.Context, *SearchUserTraitsRequest) (*SearchUserTraitsResponse, error)
	GetUsersByTraits(context.Context, *SearchUserTraitsRequest) (*UserListResponse, error)
	GetUsersByAggregatedTraits(context.Context, *GetUsersByAggregatedTraitsRequest) (*UserListResponse, error)
	GetAggregateForUsers(context.Context, *GetAggregateForUsersRequest) (*AggregateResponse, error)
	GetUsersByEvents(context.Context, *SearchUserEventsRequest) (*UserListResponse, error)
	SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error)
	NaturalBreaks(context.Context, *NaturalBreaksRequest) (*NaturalBreaksResponse, error)
	NaturalBreaksQueried(context.Context, *NaturalBreaksQueryRequest) (*NaturalBreaksResponse, error)
	QueryUsers(context.Context, *QueryRequest) (*UserListResponse, error)
	QueryAttributes(context.Context, *QueryRequest) (*AttributeListResponse, error)
	QueryTraits(context.Context, *QueryRequest) (*TraitListResponse, error)
	QueryEvents(context.Context, *QueryRequest) (*SearchEventsResponse, error)
	AddSession(context.Context, *SessionRequest) (*SessionResponse, error)
	IdentifySession(context.Context, *IdentifySessionRequest) (*IdentifySessionResponse, error)
	GetSessions(context.Context, *GetSessionsRequest) (*SessionListResponse, error)
	LogSessionEvent(context.Context, *SessionEventRequest) (*SessionEventResponse, error)
	GetSessionEvents(context.Context, *GetSessionEventsRequest) (*SessionEventListResponse, error)
	mustEmbedUnimplementedUsersServer()
}

// UnimplementedUsersServer must be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (UnimplementedUsersServer) Create(context.Context, *NewUser) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUsersServer) Get(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUsersServer) Update(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUsersServer) Find(context.Context, *UserQuery) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedUsersServer) Delete(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUsersServer) LogEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogEvent not implemented")
}
func (UnimplementedUsersServer) AddAttribute(context.Context, *AttributeRequest) (*AttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAttribute not implemented")
}
func (UnimplementedUsersServer) AddTrait(context.Context, *TraitRequest) (*TraitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTrait not implemented")
}
func (UnimplementedUsersServer) DeleteAttribute(context.Context, *AttributeRequest) (*AttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttribute not implemented")
}
func (UnimplementedUsersServer) DeleteTrait(context.Context, *TraitRequest) (*TraitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrait not implemented")
}
func (UnimplementedUsersServer) SearchUserTraits(context.Context, *SearchUserTraitsRequest) (*SearchUserTraitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserTraits not implemented")
}
func (UnimplementedUsersServer) GetUsersByTraits(context.Context, *SearchUserTraitsRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByTraits not implemented")
}
func (UnimplementedUsersServer) GetUsersByAggregatedTraits(context.Context, *GetUsersByAggregatedTraitsRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByAggregatedTraits not implemented")
}
func (UnimplementedUsersServer) GetAggregateForUsers(context.Context, *GetAggregateForUsersRequest) (*AggregateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAggregateForUsers not implemented")
}
func (UnimplementedUsersServer) GetUsersByEvents(context.Context, *SearchUserEventsRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByEvents not implemented")
}
func (UnimplementedUsersServer) SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchEvents not implemented")
}
func (UnimplementedUsersServer) NaturalBreaks(context.Context, *NaturalBreaksRequest) (*NaturalBreaksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NaturalBreaks not implemented")
}
func (UnimplementedUsersServer) NaturalBreaksQueried(context.Context, *NaturalBreaksQueryRequest) (*NaturalBreaksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NaturalBreaksQueried not implemented")
}
func (UnimplementedUsersServer) QueryUsers(context.Context, *QueryRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUsers not implemented")
}
func (UnimplementedUsersServer) QueryAttributes(context.Context, *QueryRequest) (*AttributeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAttributes not implemented")
}
func (UnimplementedUsersServer) QueryTraits(context.Context, *QueryRequest) (*TraitListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTraits not implemented")
}
func (UnimplementedUsersServer) QueryEvents(context.Context, *QueryRequest) (*SearchEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEvents not implemented")
}
func (UnimplementedUsersServer) AddSession(context.Context, *SessionRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSession not implemented")
}
func (UnimplementedUsersServer) IdentifySession(context.Context, *IdentifySessionRequest) (*IdentifySessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdentifySession not implemented")
}
func (UnimplementedUsersServer) GetSessions(context.Context, *GetSessionsRequest) (*SessionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessions not implemented")
}
func (UnimplementedUsersServer) LogSessionEvent(context.Context, *SessionEventRequest) (*SessionEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogSessionEvent not implemented")
}
func (UnimplementedUsersServer) GetSessionEvents(context.Context, *GetSessionEventsRequest) (*SessionEventListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionEvents not implemented")
}
func (UnimplementedUsersServer) mustEmbedUnimplementedUsersServer() {}

// UnsafeUsersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServer will
// result in compilation errors.
type UnsafeUsersServer interface {
	mustEmbedUnimplementedUsersServer()
}

func RegisterUsersServer(s grpc.ServiceRegistrar, srv UsersServer) {
	s.RegisterService(&Users_ServiceDesc, srv)
}

func _Users_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Create(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Get(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Update(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Find(ctx, req.(*UserQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Delete(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_LogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).LogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_LogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).LogEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_AddAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_AddAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddAttribute(ctx, req.(*AttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_AddTrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddTrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_AddTrait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddTrait(ctx, req.(*TraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_DeleteAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteAttribute(ctx, req.(*AttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteTrait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteTrait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_DeleteTrait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteTrait(ctx, req.(*TraitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SearchUserTraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserTraitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SearchUserTraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_SearchUserTraits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SearchUserTraits(ctx, req.(*SearchUserTraitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUsersByTraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserTraitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUsersByTraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUsersByTraits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUsersByTraits(ctx, req.(*SearchUserTraitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUsersByAggregatedTraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByAggregatedTraitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUsersByAggregatedTraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUsersByAggregatedTraits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUsersByAggregatedTraits(ctx, req.(*GetUsersByAggregatedTraitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetAggregateForUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAggregateForUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetAggregateForUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetAggregateForUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetAggregateForUsers(ctx, req.(*GetAggregateForUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetUsersByEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetUsersByEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetUsersByEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetUsersByEvents(ctx, req.(*SearchUserEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_SearchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).SearchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_SearchEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).SearchEvents(ctx, req.(*SearchEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_NaturalBreaks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NaturalBreaksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).NaturalBreaks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_NaturalBreaks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).NaturalBreaks(ctx, req.(*NaturalBreaksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_NaturalBreaksQueried_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NaturalBreaksQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).NaturalBreaksQueried(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_NaturalBreaksQueried_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).NaturalBreaksQueried(ctx, req.(*NaturalBreaksQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_QueryUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).QueryUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_QueryUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).QueryUsers(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_QueryAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).QueryAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_QueryAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).QueryAttributes(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_QueryTraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).QueryTraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_QueryTraits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).QueryTraits(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_QueryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).QueryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_QueryEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).QueryEvents(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_AddSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_AddSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_IdentifySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).IdentifySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_IdentifySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).IdentifySession(ctx, req.(*IdentifySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetSessions(ctx, req.(*GetSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_LogSessionEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).LogSessionEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_LogSessionEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).LogSessionEvent(ctx, req.(*SessionEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_GetSessionEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetSessionEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Users_GetSessionEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetSessionEvents(ctx, req.(*GetSessionEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Users_ServiceDesc is the grpc.ServiceDesc for Users service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Users_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userapi.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Users_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Users_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Users_Update_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _Users_Find_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Users_Delete_Handler,
		},
		{
			MethodName: "LogEvent",
			Handler:    _Users_LogEvent_Handler,
		},
		{
			MethodName: "AddAttribute",
			Handler:    _Users_AddAttribute_Handler,
		},
		{
			MethodName: "AddTrait",
			Handler:    _Users_AddTrait_Handler,
		},
		{
			MethodName: "DeleteAttribute",
			Handler:    _Users_DeleteAttribute_Handler,
		},
		{
			MethodName: "DeleteTrait",
			Handler:    _Users_DeleteTrait_Handler,
		},
		{
			MethodName: "SearchUserTraits",
			Handler:    _Users_SearchUserTraits_Handler,
		},
		{
			MethodName: "GetUsersByTraits",
			Handler:    _Users_GetUsersByTraits_Handler,
		},
		{
			MethodName: "GetUsersByAggregatedTraits",
			Handler:    _Users_GetUsersByAggregatedTraits_Handler,
		},
		{
			MethodName: "GetAggregateForUsers",
			Handler:    _Users_GetAggregateForUsers_Handler,
		},
		{
			MethodName: "GetUsersByEvents",
			Handler:    _Users_GetUsersByEvents_Handler,
		},
		{
			MethodName: "SearchEvents",
			Handler:    _Users_SearchEvents_Handler,
		},
		{
			MethodName: "NaturalBreaks",
			Handler:    _Users_NaturalBreaks_Handler,
		},
		{
			MethodName: "NaturalBreaksQueried",
			Handler:    _Users_NaturalBreaksQueried_Handler,
		},
		{
			MethodName: "QueryUsers",
			Handler:    _Users_QueryUsers_Handler,
		},
		{
			MethodName: "QueryAttributes",
			Handler:    _Users_QueryAttributes_Handler,
		},
		{
			MethodName: "QueryTraits",
			Handler:    _Users_QueryTraits_Handler,
		},
		{
			MethodName: "QueryEvents",
			Handler:    _Users_QueryEvents_Handler,
		},
		{
			MethodName: "AddSession",
			Handler:    _Users_AddSession_Handler,
		},
		{
			MethodName: "IdentifySession",
			Handler:    _Users_IdentifySession_Handler,
		},
		{
			MethodName: "GetSessions",
			Handler:    _Users_GetSessions_Handler,
		},
		{
			MethodName: "LogSessionEvent",
			Handler:    _Users_LogSessionEvent_Handler,
		},
		{
			MethodName: "GetSessionEvents",
			Handler:    _Users_GetSessionEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
